kino/urls.py
from django.contrib import admin
from django.urls import path

from baza import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name='index'),
    path("persons/", views.person_function_view, name='persons'),
    path("movie/", views.MovieView.as_view(), name='movie'),
    path("role/", views.RoleView.as_view(), name='role'),
    path("add_role/", views.AddRoleView.as_view(), name='add_role'),
    path("persons_by_class/", views.PersonView.as_view(), name='persons_by_class'),
    path("edit_person/<int:id>/", views.PersonEditView.as_view(), name='edit_person'),
    path("delete_person/<int:id>/", views.DeletePersonView.as_view(), name='delete_person'),
    path("session/", views.SessionView.as_view(), name='session'),
    path("cookiee/", views.CookieeView.as_view(), name='cookie'),
]

baza/models.py
from django.db import models
# Create your models here.
class Person(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Movie(models.Model):
    title = models.CharField(max_length=100)
    year = models.IntegerField()
    director = models.ForeignKey(Person, on_delete=models.CASCADE, related_name="directed_by")
    screenplay = models.ForeignKey(Person, on_delete=models.CASCADE, related_name="writen_by")
    actors = models.ManyToManyField(Person, related_name='roles', through='Role')



class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.PROTECT)
    role = models.CharField(max_length=128)

baza/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View

from baza.models import Person, Movie, Role


def index(request):
    return render(request, "base.html", {'title': 'dupa'})


def person_function_view(request):
    error = ""
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        if first_name != "" and last_name != "":
            Person.objects.create(first_name=first_name, last_name=last_name)
        else:
            error = "nie moze być wartości pustej"
    persons = Person.objects.all()
    context = {'persons': persons, "error": error}
    http_response = render(request, "persons.html", context)
    return http_response


class PersonView(View):

    def get(self, request):
        persons = Person.objects.all()
        context = {'persons': persons, }
        http_response = render(request, "persons.html", context)
        return http_response

    def post(self, request):
        error = ""
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        if first_name != "" and last_name != "":
            Person.objects.create(first_name=first_name, last_name=last_name)
        else:
            error = "nie moze być wartości pustej"
        return redirect("persons")


class PersonEditView(View):

    def get(self, request, id):
        person = Person.objects.get(pk=id)
        movies = Movie.objects.all()
        return render(request, 'persons.html', {'person': person, 'movies':movies})

    def post(self, request, id):
        person = Person.objects.get(pk=id)
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        person.first_name = first_name
        person.last_name = last_name
        person.save()
        return redirect('persons')


class DeletePersonView(View):

    def get(self, request, id):
        person = Person.objects.get(pk=id)
        return render(request, 'persons_delete.html', {'person': person})

    def post(self, request, id):
        odp = request.POST.get('submit')
        if odp == "ok":
            person = Person.objects.get(pk=id)
            person.delete()
        return redirect('persons')

class MovieView(View):

    def get(self, request):
        persons = Person.objects.all()
        movies = Movie.objects.all()
        return render(request, "movie.html", {'persons':persons, 'movies':movies})

    def post(self, request):
        title = request.POST['title']
        year = request.POST['year']
        screenplay_id = request.POST['screenplay']
        director_id = request.POST['director']

        screenplay = Person.objects.get(pk=screenplay_id)
        director = Person.objects.get(pk=director_id)
        m = Movie.objects.create(title=title, year=year, screenplay=screenplay, director=director)
        m.actors.set([1,2,3])
        return redirect('movie')


class RoleView(View):

    def get(self, request):
        persons = Person.objects.all()
        movies = Movie.objects.all()
        return render(request, "role.html", {'persons':persons, 'movies':movies})

    def post(self, request):
        movie = Movie.objects.get(id=request.POST['movie'])
        actor = Person.objects.get(id=request.POST['actor'])
        role = request.POST['role']
        Role.objects.create(movie=movie, person=actor, role=role)
        return redirect('role')

class AddRoleView(View):

    def post(self, request):
        person = Person.objects.get(id = request.POST['person'])
        movie = Movie.objects.get(id=request.POST['movie'])
        role = request.POST['role']
        Role.objects.create(movie=movie, person=person, role=role)
        return redirect('edit_person', person.id)


class SessionView(View):

    def get(self, request):
        session = request.session
        return render(request, 'session.html', {'session':session})

    def post(self, request):
        key = request.POST['key']
        value = request.POST['value']
        request.session[key] = value
        return redirect('session')


class CookieeView(View):

    def get(self, request):
        cookiee = request.COOKIES
        return render(request, 'cookie.html', {'cookiee':cookiee})

    def post(self, request):
        key = request.POST['key']
        value = request.POST['value']
        httpresponse = redirect('cookie')
        httpresponse.set_cookie(key, value)
        return httpresponse

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{title}}</title>
</head>
<body>
<ul>
    <li><a href="{% url 'index'%}">Home</a> </li>
    <li><a href="{% url 'persons'%}">Osoby</a> </li>
    <li><a href="{% url 'persons_by_class'%}">Osoby przez Klase</a> </li>
    <li><a href="{% url 'movie'%}">Filmy</a> </li>
    <li><a href="{% url 'role'%}">Role</a> </li>
</ul>
{% block content %}
{% endblock %}

</body>
</html>

templates/cookie.html
<form method="post">
    {% csrf_token %}
    <p>kucz: <input type="text" name="key"> </p>
    <p>wartosc: <input type="text" name="value"> </p>
    <input type="submit">
</form>

{% for key, value in cookiee.items %}
    <p>cookiee[{{ key }}]={{ value }}</p>
{% endfor %}

templates/movie.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        <p>Tytuł: <input type="text" name="title"></p>
        <p>Rok: <input type="number" name="year"></p>
        <p>reżyser:
            <select name="director">
                {% for person in persons %}
                <option value="{{ person.id }}">{{ person }}</option>
                {% endfor %}
            </select>
        </p>
        <p>scenarzysta:
            <select name="screenplay">
                {% for person in persons %}
                    <option value="{{ person.id }}">{{ person }}</option>
                {% endfor %}
            </select>
        </p>
        <p>aktorzy:
                <ul>
                {% for person in persons %}
                    <li> <input type="checkbox" value="{{ person.id }}" name="actors"> {{ person }}</li>
                {% endfor %}
                </ul>

        </p>
        <input type="submit">
    </form>
    <table>
    <tr>
        <th>Tytuł</th><th>Rok Produkcji</th><th> Reżyseria</th><th>scenariusz</th> <th>Wystąpili</th></tr>
        {% for movie in movies %}
            <tr><td> {{ movie.title }}</td>
                <td> {{ movie.year }}</td>
                <td> {{ movie.director }}</td>
                <td> {{ movie.screenplay }}</td>
                <td><ul>
                    {% for role in movie.role_set.all %}
                        <li> {{ role.person }} jako {{ role.role }}</li>
                    {% endfor %}
                </ul>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/persons.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ error }}</h2>
    <form method="post">
        {% csrf_token %}
        <p>
            Imie: <input type="text" name="first_name" value="{{ person.first_name }}">
        </p>
        <p>
            Nazwisko: <input type="text" name="last_name" value="{{ person.last_name }}">
        </p>
        <p>
            <input type="submit">
        </p>
    </form>

    <ul>
        {% for person in persons %}
            <li>
                <a href="{% url 'edit_person' person.id %}"> {{ person }}</a>
                <a href="{% url 'delete_person' person.id %}">Usuń</a>
            </li>
        {% endfor %}
    </ul>
    {% if person %}
        <form method="post" action="{% url 'add_role' %}">
            {% csrf_token %}
            <input type="text" name="role">
            <select name="movie">
                {% for movie in movies %}
                    <option value="{{ movie.id }}">{{ movie.title }}</option>
                {% endfor %}
            </select>
            <input type="hidden" name="person" value="{{ person.id }}">
            <input type="submit">
        </form>
    {% endif %}
{% endblock %}

templates/persons_delete.html
{% extends 'base.html' %}
{% block content %}
    <p>Czy jesteś pewien że chesz usunąć Osobe {{ person }} ?</p>
    <form method="post">
    {% csrf_token %}
        <p><input type="submit" name="submit" value="ok">
        <input type="submit" name="submit" value="Nope"></p>
    </form>
{% endblock %}

templates/role.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
    aktor:
        <select name="actor">
            {% for person in persons %}
                <option value="{{ person.id }}">{{ person }}</option>
            {% endfor %}
        </select>
    film:
        <select name="movie">
            {% for movie in movies %}
                <option value="{{ movie.id }}">{{ movie.title }}</option>
            {% endfor %}
        </select>
        rola: <input type="text" name="role">
    <input type="submit">
    </form>
{% endblock %}

templates/session.html
<form method="post">
    {% csrf_token %}
    <p>kucz: <input type="text" name="key"> </p>
    <p>wartosc: <input type="text" name="value"> </p>
    <input type="submit">
</form>

{% for key, value in session.items %}
    <p>session[{{ key }}]={{ value }}</p>
{% endfor %}